package com.issueflow.audit;

public enum AuditAction {
    USER_CREATE,
    USER_UPDATE,
    USER_DELETE,

    PROJECT_CREATE,
    PROJECT_UPDATE,
    PROJECT_DELETE,
    PROJECT_RESTORE,

    TICKET_CREATE,
    TICKET_UPDATE,
    TICKET_DELETE,
    TICKET_RESTORE,

    COMMENT_CREATE,
    COMMENT_UPDATE,
    COMMENT_DELETE,

    ATTACHMENT_UPLOAD,
    ATTACHMENT_DELETE,

    AUTO_ASSIGN,
    AUTO_ESCALATE
}
